#!/usr/bin/env bash
#configures a new Ubuntu machine nginx
apt-get update
apt-get install software-properties-common -y
add-apt-repository ppa:vbernat/haproxy-1.7 -y
apt-get update
apt-get install haproxy=1.7.\* -y
echo "frontend web-front
        bind *:80
        default_backend web-backend

backend web-backend
        balance roundrobin
        12481-web-01 107.23.96.232 check
        12481-web-02 18.233.66.214 check
" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy start
