#!/usr/bin/env bash

# Update package lists and install HAProxy
sudo apt-get update
sudo apt-get install -y haproxy

# Backup the default HAProxy configuration file
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original

# Create a new HAProxy configuration file
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOL
global
    log 127.0.0.1 local0 notice
    maxconn 2000
    user haproxy
    group haproxy

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    retries 3
    option  redispatch
    timeout connect 10s
    timeout client  15s
    timeout server  15s

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server 12481-web-01 107.23.96.232:80 check
    server 12481-web-02 18.233.66.214:80 check
EOL

# Enable HAProxy to start on boot
sudo systemctl enable haproxy

# Restart HAProxy service
sudo systemctl restart haproxy
