#!/usr/bin/env bash
#Bash script that displays numbers from 1 to 100.

for ((number=1;number<=100;number++));do
if [[ "$((number%3))" == "0"  && "$((number%5))" != "0" ]]; then
    echo "Fizz"
elif [[ "$((number%5))" == "0"  && "$((number%3))" != "0" ]]; then
    echo "Buzz"
elif [[ "$((number%5))" == "0" &&  "$((number%3))" == "0" ]]; then
    echo "FizzBuzz"
else
    echo "$number"
fi
done
